url: https://code-n-kids.github.io
baseurl: 

# Site settings
title: Code'n'Kids
email: dingy@code-n-kids.org
description: "Code'n'Kids"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Xavier Bourguignon
  pic: 1
  position: Président & Animateur
  social:
    - title: twitter
      url: http://twitter.com/xbourguignon
    - title: linkedin
      url: http://ch.linkedin.com/in/xavierbourguignon
- name: Emilie Vuichard
  pic: 3
  position: Secrétaire
  social:
- name: Carine Nicollier
  pic: 2
  position: Trésorière
  social:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/code-n-kids
  - title: github
    url: http://github.com/Code-N-Kids

# Postal address (add as many lines as necessary)
address:
  - line: 162 route des Presels
  - line: 74520 Dingy En Vuache

# Build settings
markdown: kramdown
permalink: pretty